debian/changelog, debian/control
=> chore: release dcc-insider-plugin 0.0.1

CMakeLists.txt, debian/control, insidermodule.cpp, insidermodule.h, pkutils.cpp, pkutils.h
使用 QCoro 进行 packagekit 相关的异步操作
=> refactor: use QCoro for async packagekit transactions

insidermodule.cpp, insidermodule.h, translations/dcc-insider-plugin.ts, translations/dcc-insider-plugin_zh_CN.ts
=> feat: support dim preview

debian/changelog, debian/control, debian/copyright
=> chore: release dcc-insider-plugin 0.1.1

insidermodule.cpp
如果点击的是当前选中的 item 就 return
Issue: https://github.com/linuxdeepin/developer-center/issues/6760
=> fix: do nothing if clicked item was  checked

insidermodule.cpp, insidermodule.h
Issues linuxdeepin/developer-center#6808
=> chore: hide input method in x11

insidermodule.cpp, insidermodule.h
we must set item status before show(hide) the new input method
Log:
=> fix: there is a delay when switch to deepin im

insidermodule.cpp
hide new input method when display manager is lightdm or is not dim
Log:
=> fix: switch to deepin im flashing when switch to treeland first

debian/changelog
=> chore: release 0.1.3

debian/changelog, insidermodule.cpp, insidermodule.h
=> release 0.1.4

dcc-insider-plugin/insidermodule.cpp, dcc-insider-plugin/insidermodule.h, dcc-insider/operation/dccinsider.h, dcc-insider/operation/insiderworker.cpp, dcc-insider/operation/insiderworker.h
Switch to treeland to add installation of ddm package
Log:
Bug: https://pms.uniontech.com/bug-view-282591.html
=> fix: Switch to treeland to add installation of ddm package

debian/changelog
release 0.1.5
Log: bump version to 0.1.5
=> chore: bump version to 0.1.5

dcc-insider/operation/insiderworker.cpp, dcc-insider/operation/insiderworker.h, dcc-insider/qml/insiderMain.qml, dcc-insider/translations/insider.ts, dcc-insider/translations/insider_az.ts, dcc-insider/translations/insider_bo.ts, dcc-insider/translations/insider_ca.ts, dcc-insider/translations/insider_es.ts, dcc-insider/translations/insider_fi.ts, dcc-insider/translations/insider_fr.ts, dcc-insider/translations/insider_hu.ts, dcc-insider/translations/insider_it.ts, dcc-insider/translations/insider_ja.ts, dcc-insider/translations/insider_ko.ts, dcc-insider/translations/insider_nb_NO.ts, dcc-insider/translations/insider_pl.ts, dcc-insider/translations/insider_pt_BR.ts, dcc-insider/translations/insider_ru.ts, dcc-insider/translations/insider_uk.ts, dcc-insider/translations/insider_zh_CN.ts, dcc-insider/translations/insider_zh_HK.ts, dcc-insider/translations/insider_zh_TW.ts
=> feat: Add display manager switch notification

dcc-insider/qml/ViewItem.qml, dcc-insider/qml/insiderMain.qml
Adapt to the UI style of the control center
pms: TASK-361721
=> fix: Adapt to the UI style of the control center

debian/changelog
release 0.1.7
Log: bump version to 0.1.7
=> chore: bump version to 0.1.7

dcc-insider/qml/insiderMain.qml, dcc-insider/translations/insider.ts, dcc-insider/translations/insider_az.ts, dcc-insider/translations/insider_bo.ts, dcc-insider/translations/insider_ca.ts, dcc-insider/translations/insider_es.ts, dcc-insider/translations/insider_fi.ts, dcc-insider/translations/insider_fr.ts, dcc-insider/translations/insider_hu.ts, dcc-insider/translations/insider_it.ts, dcc-insider/translations/insider_ja.ts, dcc-insider/translations/insider_ko.ts, dcc-insider/translations/insider_nb_NO.ts, dcc-insider/translations/insider_pl.ts, dcc-insider/translations/insider_pt_BR.ts, dcc-insider/translations/insider_ru.ts, dcc-insider/translations/insider_uk.ts, dcc-insider/translations/insider_zh_CN.ts, dcc-insider/translations/insider_zh_HK.ts, dcc-insider/translations/insider_zh_TW.ts, debian/changelog
=> fix: Update display manager Name

dcc-insider/qml/insiderMain.qml, dcc-insider/translations/insider.ts, dcc-insider/translations/insider_az.ts, dcc-insider/translations/insider_bo.ts, dcc-insider/translations/insider_ca.ts, dcc-insider/translations/insider_es.ts, dcc-insider/translations/insider_fi.ts, dcc-insider/translations/insider_fr.ts, dcc-insider/translations/insider_hu.ts, dcc-insider/translations/insider_it.ts, dcc-insider/translations/insider_ja.ts, dcc-insider/translations/insider_ko.ts, dcc-insider/translations/insider_nb_NO.ts, dcc-insider/translations/insider_pl.ts, dcc-insider/translations/insider_pt_BR.ts, dcc-insider/translations/insider_ru.ts, dcc-insider/translations/insider_uk.ts, dcc-insider/translations/insider_zh_CN.ts, dcc-insider/translations/insider_zh_HK.ts, dcc-insider/translations/insider_zh_TW.ts
=> chore: Update Treeland VM usage and Wine support notice

debian/changelog
release 0.1.9
Log: bump version to 0.1.9
=> chore: bump version to 0.1.9

dcc-insider/operation/dccinsider.cpp, dcc-insider/operation/dccinsider.h, dcc-insider/qml/insiderMain.qml
Not displayed when live system
pms: BUG-300369
=> fix: Not displayed when live system

debian/changelog
release 0.1.10
Log: bump version to 0.1.10
=> chore: bump version to 0.1.10

debian/changelog
release 0.1.11
Log: bump version to 0.1.11
=> chore: bump version to 0.1.11

debian/changelog
release 0.1.12
Log: bump version to 0.1.12
=> chore: bump version to 0.1.12

debian/changelog
=> chore: bump version to 0.1.15
